disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
